# Generated by Django 3.0.4 on 2020-03-21 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketUser',
            fields=[
                ('connection_id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('can_vibrate', models.BooleanField()),
            ],
        ),
    ]
