/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package veebrate;

import org.junit.Test;
import static org.junit.Assert.*;
import io.vertx.core.Vertx;
import io.vertx.ext.web.client.WebClient;
import io.vertx.core.http.HttpServer;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestOptions;
import io.vertx.ext.unit.TestSuite;
import io.vertx.ext.unit.report.ReportOptions;

public class AppTest {
//   public static void main(String[] args) {
//     new ServerTest().run();
//   }

  Vertx vertx;

  @Test public void run() {

    TestOptions options = new TestOptions().addReporter(new ReportOptions().setTo("console"));
    TestSuite suite = TestSuite.create("veebrate.test.ServerTest");

    suite.before(context -> {
      vertx = Vertx.vertx();
      vertx.createHttpServer().requestHandler(req -> req.response().end("foo")).listen(8080, context.asyncAssertSuccess());
    });

    suite.after(context -> {
      vertx.close(context.asyncAssertSuccess());
    });

    // Specifying the test names seems ugly...
    suite.test("some_test1", context -> {
      // Send a request and get a response
      Async async = context.async();
      vertx.eventBus().consumer("chat.messageIn", msg -> {
        async.complete();
      });
    });

    suite.run(options);
  }
}
